### ISSUE TITLE
Possibile php 7.1.x Compatibility issue

### ISSUE THREAD

**Issue by widoz** [churchthemes/widget-importer-exporter#10]
I got the following errors running WordPress 4.7 and php7.1.x

`
Warning: Illegal string offset 'wp_inactive_widgets' in /{plugin-path}/widget-importer-exporter/includes/import.php on line 260

Fatal error: Uncaught Error: Cannot use string offset as an array in /{plugin-path}/widget-importer-exporter/includes/import.php:260 Stack trace: #0 /{plugin-path}/widget-importer-exporter/includes/import.php(97): wie_import_data(Object(stdClass)) #1 /{plugin-path}/widget-importer-exporter/includes/import.php(58): wie_process_import_file('/{file-path}...') #2 wp-includes/class-wp-hook.php(298): wie_upload_import_file('') #3 wp-includes/class-wp-hook.php(323): WP_Hook->apply_filters(NULL, Array) #4 wp-includes/plugin.php(453): WP_Hook->do_action(Array) #5 wp-admin/admin.php(212): do_action('load-tools_page...') #6 wp-admin/tools.php(10): require_once('/{file-path}/...') #7 {main} thrown in /{plugin-path}/widget-importer-exporter/includes/import.php on line 260`

**Comment by widoz** [comment]
I think this would solve the issue.
Casting the option to be an array. Even If I'll prefer to check the option and in case is false make the $sidebars_widgets an empty array.

`$sidebars_widgets = (array) get_option( 'sidebars_widgets' ); // which sidebars have which widgets, get fresh every time`

**Comment by stevengliebe** [comment]
Thanks for catching this. It will be good to resolve this before PHP 7.1 becomes common. Please submit a pull request if you would like to. If you don't have time, I can just patch it in. Let me know.

**Comment by widoz** [comment]
Hi, thank you to taking care this. I can make a pull request but I've only a doubt about the use of the ?: ( elvis ) operator for backward compatibility.

Would be ok to use it or a traditional if would be better? For example, we can get the value and perform a check like this.

`
$sidebars_widgets = get_option( 'sidebars_widgets' );

if (! $sidebars_widgets()) {
    $sidebars_widgets = array();
}
`

Assumed that if there is a value is an array, if is false instead of casting it that will produce an array with one element with value to "false" we change it. I need only to make some test about the use of the if because of php7 may create problem with the new typing.

**Comment by stevengliebe** [comment]
Let's go with the latter. Better safe than sorry. Thanks for working on this.

**Comment by widoz** [comment]
Hi,

I made some test and I discovered that the issue doesn't happen because of php7.1 but when the option **sidebars_widgets** is empty.

Usually when you create a site the option will be populated with:

`a:3:{s:19:"wp_inactive_widgets";a:0:{}s:9:"sidebar-1";a:6:{i:0;s:8:"search-2";i:1;s:14:"recent-posts-2";i:2;s:17:"recent-comments-2";i:3;s:10:"archives-2";i:4;s:12:"categories-2";i:5;s:6:"meta-2";}s:13:"array_version";i:3;}`

The issue appeared because for some reason my option was empty.
So, I think this is a rarely case and may be more a bug made by another plugin or theme or probably a mistake by user.

By the way, I made the pull request.

**Comment by stevengliebe** [comment]
Thank you, merged your pull request.
