### ISSUE TITLE
"You must upload a .wie file generated by this plugin." error

### ISSUE THREAD

**Issue by Anakas** [churchthemes/widget-importer-exporter#12]
env: WordPress 4.7.1 and php7.1.x

I got the following error when I imported a [.wie] file that this plugin itself has just created.  
"You must upload a .wie file generated by this plugin."

I found a issue when I checked the source files.

If  'finfo_file' function is available, 'wp_check_filetype_and_ext' function cannot recognise properly
the filetype of 'application/json'.
This plugin is using 'wp_check_filetype_and_ext' in  'wie_upload_import_file' for import and  return the type error.

What can I do for this issue?

**Comment by stevengliebe** [comment]
This is caused by a known bug in WordPress 4.7.1 that affects uploads in general. Please see this for a simple workaround (and additional details) until WordPress 4.7.2 is released.

https://wordpress.org/support/topic/solution-for-wp-4-7-1-bug-causing-you-must-upload-a-wie-file-generated-by/

**Comment by Anakas** [comment]
Thank you for your reply, and  I'm sorry that I didn't know that bug information.
I will try the workaround untli next release.

**Comment by stevengliebe** [comment]
No problem, thank you for reporting anyway.
