### ISSUE TITLE
Import fails when finfo_file exists due to wp_check_filetype_and_ext

### ISSUE THREAD

**Issue by pcfreak30** [churchthemes/widget-importer-exporter#13]
The `wp_check_filetype_and_ext` returns false for ` $wp_filetype['ext']` and `$wp_filetype['type']`.

its comparing `text/plain` to `application/json`.

**Comment by stevengliebe** [comment]
Please see #12. This is a bug with WordPress 4.7.1 affecting uploads in general and there is a workaround until 4.7.2 is released. Thank you for reporting.
