### ISSUE TITLE
suggest to use WordPress coding standard

### ISSUE THREAD

**Issue by widoz** [churchthemes/widget-importer-exporter#17]
As per title, do you think is possible to introduce the wordpress coding standards using the wpcs srandard lib for phpcs?

If you want I can make the changes.

**Comment by stevengliebe** [comment]
Feel free to make a pull request with cleaned up code and I'll look it over. I'd like to start using phpcs/wpcs with Sublime Text but running into trouble today; will revisit later.

**Comment by widoz** [comment]
Thank you.

I applied and verified the whole plugin code for make it wpcs compliant.

Pull request here https://github.com/churchthemes/widget-importer-exporter/pull/19

**Comment by stevengliebe** [comment]
Thank you for doing this. I'm merging it.
