### ISSUE TITLE
WP 5.0.1

### ISSUE THREAD

**Issue by tomusborne** [churchthemes/widget-importer-exporter#23]
It seems the fix released last night prevents the `application/json` type from being uploaded.

I'm getting a white page with the type when trying to upload on a fresh WP install with no plugins activated: http://prntscr.com/lulfv6

**Comment by stevengliebe** [comment]
Thank you. It looks like 5.0 changed MIME verification: https://make.wordpress.org/core/2018/12/13/backwards-compatibility-breaks-in-5-0-1/

**Comment by tomusborne** [comment]
Yea, the `$real_mime` check for the `.wie` file is coming back with `text/plain`.

If `'wie' => 'text/plain'` is passed within `$overrides` when the file is uploaded, it passes.

Of course, you may have a better idea.

**Comment by stevengliebe** [comment]
I released 1.5.4 along those lines. Do you want to give it a test?

**Comment by tomusborne** [comment]
Looks good to me 👍

**Comment by stevengliebe** [comment]
Thanks for confirming. That'll save me some time on support tomorrow morning!
