### ISSUE TITLE
disable all widgets

### ISSUE THREAD

**Issue by geniushostuk** [churchthemes/widget-importer-exporter#26]

**Comment by geniushostuk** [comment]
I disabled all widgets and downloaded the export file.

when i try to import the file it says the file is invalid.

**Comment by stevengliebe** [comment]
Please make a post on the WordPress forum for the Widget Importer & Exporter plugin and copy and paste the exact error message you receive.

https://wordpress.org/support/plugin/widget-importer-exporter/
